kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nb-culler
subjects:
  - kind: ServiceAccount
    name: nb-culler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nb-culler
