apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: assign-class-label-webhook
webhooks:
- name: assign-class-label-webhook.nerc.com
  clientConfig:
    service:
      namespace: rhods-notebooks
      name: assign-class-label-webhook
      path: /mutate
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURvakNDQW9xZ0F3SUJBZ0lVTlpUUGJOMVNBdnNzVUdUTHRUQW1FamE5TmJzd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1FqRUxNQWtHQTFVRUJoTUNXRmd4RlRBVEJnTlZCQWNNREVSbFptRjFiSFFnUTJsMGVURWNNQm9HQTFVRQpDZ3dUUkdWbVlYVnNkQ0JEYjIxd1lXNTVJRXgwWkRBZUZ3MHlOREE1TVRjeE5ESXlNekZhRncweU56QTNNRGd4Ck5ESXlNekZhTUVJeEN6QUpCZ05WQkFZVEFsaFlNUlV3RXdZRFZRUUhEQXhFWldaaGRXeDBJRU5wZEhreEhEQWEKQmdOVkJBb01FMFJsWm1GMWJIUWdRMjl0Y0dGdWVTQk1kR1F3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQgpEd0F3Z2dFS0FvSUJBUUN3Z2RyWGVSek1BYW1TT1hwYnB1a0dsdTdBL1lpVTl1bytZbTI1Zm9aRmhrQXBJeWY1CkNCNzIzRW0wbUtrdmdtR0VjYy9oZ1kwYUxnV3dHZTBGRW40ZjZGQ21RRjJzMlRHMEJPUDZ4Z3NjUHlGMU41NmgKKzRwVnE4UXFrbTA3YktxcEhZSzF2czVTd2tNTXExYjBZWjdBd0Rjd3p6VWtWM20zb0VtSnptR2U1L1JUd1puTApGdlg0LzRsUEdkMGF6MnBlUnBudllOOWZLQWd3bERxMklFdjJJZUljTWpOMmxVQTAxYkhGc09qZXAyakU1dWQrCi9DWmwxZHRuWkJYWWY1N01DNFc2MitmZnlRWExyOGt1clNUN0Z5Zi9OTjVRblhxNDBQSHd4N3dWOHlzY3l6M2sKWmRsalBiTHBMQTJYeE5ZcXJRMDBid1FDVS9kVTVPZ0VaZVU3QWdNQkFBR2pnWTh3Z1l3d0hRWURWUjBPQkJZRQpGUDBobG4xTGs0aXcwUTNwTnVUNVNsWHNKdDYvTUI4R0ExVWRJd1FZTUJhQUZQMGhsbjFMazRpdzBRM3BOdVQ1ClNsWHNKdDYvTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3T1FZRFZSMFJCREl3TUlJdVlYTnphV2R1TFdOc1lYTnoKTFd4aFltVnNMWGRsWW1odmIyc3VjbWh2WkhNdGJtOTBaV0p2YjJ0ekxuTjJZekFOQmdrcWhraUc5dzBCQVFzRgpBQU9DQVFFQVNSdWZpcDI3TmFQVC8wZGZ5VU85MDMxV2F6Z3U0YzY4dG1FVXlBYXpvNlY2Z1lzK005YnVERDNJCkl3ZkkvUXB5bGhIb01EZ3FjcjlyZ1NHY2lvbTFocXM4RjAyNGFaa3BobzV3LzRiSUJ2VWVUVHVKNlhyYzhJOCsKSW1ESHh1SFREVXZ4bG15U0NWc0lOSlBUZWprQ0RQRVR0bVlzaHlNZkxyM1NOYUZSYXU4VlNqUFNsd2VDNVkzUQo4Q3I0Q2V0eHlCdlp0enhpTXZvemR0dGx3d3RGejRaMmQ5ZmRIWmZWbms5UFlqZFpRb3o1cVlBbklkcGlJemo3Ci92UUxQZ1RpbmRDWkIvTW1PbHRBZ0UrNmQrQ2lsOW1yOHlRVVlTdlYzL015SUU1ZDd5M0h0VnJrRnhKYkZqNjEKVjVpOUR1YWNpTXpMUVM2UzJOUUJkcFpINzc0NHZ3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  rules:
    - operations: ["CREATE"]
      apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values:
          - rhods-notebooks
  sideEffects: None
  admissionReviewVersions: ["v1"]
