apiVersion: batch/v1
kind: CronJob
metadata:
  name: group-sync
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          name: group-sync
        spec:
          serviceAccountName: group-sync
          containers:
          - name: group-sync
            image: ghcr.io/ocp-on-nerc/bu-rhoai:toolkit  
            command: ["python", "group-sync.py"]
            env:
            # EDIT VALUE HERE BEFORE RUNNING
            - name: GROUP_NAME
              value: <group>
            # EDIT VALUE HERE BEFORE RUNNING
            - name: NAMESPACE
              value: <namespace>
            imagePullPolicy: Always
          restartPolicy: Never  
  successfulJobsHistoryLimit: 7
  failedJobsHistoryLimit: 7

