apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: delete-notebook-job
rules:
- apiGroups:
  - user.openshift.io
  resources:
  - groups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubeflow.org
  resources:
  - notebooks
  verbs:
  - get
  - list
  - watch
  - delete
  - patch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
